# Add application configuration variables here, as shown below.
SENDGRID_USERNAME: YYYYYYYYYY
SENDGRID_PASSWORD: YYYYYYYYYY
S3_KEY_ID: XXXXXXXXXXXXXXXXXXXXXXX
S3_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXX
GOOGLE_KEY: ZZZZZZZZZZZZZZZZZZZZ
GOOGLE_SECRET: ZZZZZZZZZZZZZZZZZZZZ
FACEBOOK_APP_ID: WWWWWWWWWWWWWWWWWWWWW
FACEBOOK_SECRET: WWWWWWWWWWWWWWWWWWWWW