require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MaturesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Mature. As you add validations to Mature, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MaturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all matures as @matures" do
      mature = Mature.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:matures)).to eq([mature])
    end
  end

  describe "GET #show" do
    it "assigns the requested mature as @mature" do
      mature = Mature.create! valid_attributes
      get :show, {:id => mature.to_param}, valid_session
      expect(assigns(:mature)).to eq(mature)
    end
  end

  describe "GET #new" do
    it "assigns a new mature as @mature" do
      get :new, {}, valid_session
      expect(assigns(:mature)).to be_a_new(Mature)
    end
  end

  describe "GET #edit" do
    it "assigns the requested mature as @mature" do
      mature = Mature.create! valid_attributes
      get :edit, {:id => mature.to_param}, valid_session
      expect(assigns(:mature)).to eq(mature)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Mature" do
        expect {
          post :create, {:mature => valid_attributes}, valid_session
        }.to change(Mature, :count).by(1)
      end

      it "assigns a newly created mature as @mature" do
        post :create, {:mature => valid_attributes}, valid_session
        expect(assigns(:mature)).to be_a(Mature)
        expect(assigns(:mature)).to be_persisted
      end

      it "redirects to the created mature" do
        post :create, {:mature => valid_attributes}, valid_session
        expect(response).to redirect_to(Mature.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved mature as @mature" do
        post :create, {:mature => invalid_attributes}, valid_session
        expect(assigns(:mature)).to be_a_new(Mature)
      end

      it "re-renders the 'new' template" do
        post :create, {:mature => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mature" do
        mature = Mature.create! valid_attributes
        put :update, {:id => mature.to_param, :mature => new_attributes}, valid_session
        mature.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mature as @mature" do
        mature = Mature.create! valid_attributes
        put :update, {:id => mature.to_param, :mature => valid_attributes}, valid_session
        expect(assigns(:mature)).to eq(mature)
      end

      it "redirects to the mature" do
        mature = Mature.create! valid_attributes
        put :update, {:id => mature.to_param, :mature => valid_attributes}, valid_session
        expect(response).to redirect_to(mature)
      end
    end

    context "with invalid params" do
      it "assigns the mature as @mature" do
        mature = Mature.create! valid_attributes
        put :update, {:id => mature.to_param, :mature => invalid_attributes}, valid_session
        expect(assigns(:mature)).to eq(mature)
      end

      it "re-renders the 'edit' template" do
        mature = Mature.create! valid_attributes
        put :update, {:id => mature.to_param, :mature => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested mature" do
      mature = Mature.create! valid_attributes
      expect {
        delete :destroy, {:id => mature.to_param}, valid_session
      }.to change(Mature, :count).by(-1)
    end

    it "redirects to the matures list" do
      mature = Mature.create! valid_attributes
      delete :destroy, {:id => mature.to_param}, valid_session
      expect(response).to redirect_to(matures_url)
    end
  end

end
